version: "3.9"

services:
  api:
    container_name: api
    build: .
    image: node-app:0.1
    ports:
      - 5000:5000
    depends_on:
      - database
    restart: unless-stopped

  database:
    container_name: postgres_db
    build: ./postgres-docker
    image: pg-test-database:0.1
    volumes:
      - ./postgres-docker/db-data:/var/lib/postgresql/data
    ports:
      - 4321:5432
    environment:
      POSTGRES_DB: prueba-docker
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      - database


